config/routes.rb
LancarAbadi::Application.routes.draw do

  resources :special_prices

  resources :system_languages do
    collection do
      get :change_language
      post :change_language_submit
    end
  end

  resources :report do
    collection do
      get :sale_filter
      get :sale
    end
  end

  resources :filter do
    collection do
      get :country
      get :province
      get :city
      get :unit_of_measure
      get :special_price
      get :category
      get :customer_group
      get :supplier
      get :customer
      get :product
      get :product_unit
      get :product_home
      get :purchase
      get :sale
      get :adjustment
    end
  end

  resources :adjustments do
    resources :adjustment_details do
      collection do
        get :show_product
        post :search_product
        get :pick_product
      end
    end

    member do
      get :print_barcode
      get :print_sticker
      get :import
      post :import_submit
    end
  end

  resources :sales do
    member do
      get :edit_footer
      get :print
    end
    
    collection do
      get :show_customer
      post :search_customer
      get :pick_customer
    end

    resources :sale_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :purchases do
    member do
      get :edit_footer
      get :print_barcode
      get :print_sticker
    end
    
    collection do
      get :show_supplier
      post :search_supplier
      get :pick_supplier
    end

    resources :purchase_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :customers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :customer_phones
  end

  resources :suppliers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :supplier_phones
    resources :supplier_categories
  end

  resources :products do
    collection do
      get :instant_new
      post :instant_create
      get :import
      post :import_submit
      get :generate_barcode
      post :generate_barcode_submit
      get :unit_index
    end

    member do
      get :unit_show
    end
    
    resources :product_details
    resources :product_purchases
  end

  resources :emp_date_details
  resources :emp_dates
  resources :emp_months
  resources :employees
  resources :company_profiles
  resources :stocks
  resources :user_menus
  resources :user_groups
  devise_for :users
  resources :customer_groups
  resources :unit_of_measures
  resources :categories
  resources :cities
  resources :provinces
  resources :countries

  scope "/admin" do
    resources :users
  end

  get "home/index"
  get "*module/home/provinces_by_country" => "home#provinces_by_country"
  get "*module/home/cities_by_province" => "home#cities_by_province"

  root to: "home#index"

end

app/models/purchase_detail.rb
class PurchaseDetail < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product
  belongs_to :unit_of_measure
  attr_accessible :purchase_id, :product_id, :added_discount, :amount, :discount, :price, :quantity, :quantity_print, :unit_of_measure_id

  before_save :amount_calculation
  before_save :get_quantity_print
  after_save :sub_amount_calculation
  after_destroy :sub_amount_calculation

  def product_detail
  	"#{product.try(:name)} #{product.try(:product_type)} #{product.try(:size)}-#{product.try(:merk)} (#{product.try(:barcode_id)})"
  end

  def amount_calculation
    begin
      amount = self.quantity.to_f * self.price.to_f
      amount = amount - (amount*(self.discount.to_f/100)) - self.added_discount.to_f
      self.amount = amount
    rescue
      0
    end
  end

  def sub_amount_calculation
    Purchase.find(self.purchase_id).sum_sub_amount
  end

  def get_quantity_print
    if self.quantity_print.to_i==0
      self.quantity_print=self.quantity.to_i
    end
  end
end

app/controllers/purchase_details_controller.rb
class PurchaseDetailsController < ApplicationController
  def get_data
    @purchase = Purchase.find(params[:purchase_id])
    @product_units = UnitOfMeasure.where(:id => 0)
  end

  def get_product
    # @products = Product
    # .search_product(params[:keyword])
    # .where(:supplier_id => @purchase.supplier_id)
    # .order(:name, :product_type, :merk)
    # .paginate(:page => params[:page], :per_page => 500)

    @products = Product.search_product(params[:keyword], params[:product_type], params[:merk], params[:size])
    .where(:supplier_id => @purchase.supplier_id)
    .sort_product(params[:column], params[:direction])
    .paginate(:page => params[:page], :per_page => 500)

    @keyword = params[:keyword] if params[:keyword].present?
    @product_type = params[:product_type] if params[:product_type].present?
    @merk = params[:merk] if params[:merk].present?
    @size = params[:size] if params[:size].present?
    @column = params[:column] if params[:column].present?
    @direction = params[:direction] if params[:direction].present?
  end

  def show_product
    get_data
    get_product
  end

  def search_product
    get_data
    get_product
  end

  def sort_product
    get_data
    get_product
  end

  def pick_product
    @product = Product.find(params[:product_id])
    @product_unit_default = UnitOfMeasure.find_by_id(@product.try(:unit_of_measure_id).to_i)
    @product_units = @product.details.order(:id)
    @last_purchase_price = @product.purchases.last.try(:purchase_price).to_f
  end

  # GET /purchase_details/new
  # GET /purchase_details/new.json
  def new
    get_data
    @purchase_detail = @purchase.details.new
    @purchase_detail.quantity = ""
    @purchase_detail.price = ""
    @purchase_detail.discount = ""
    @purchase_detail.quantity_print = ""
  end

  # GET /purchase_details/1/edit
  def edit
    get_data
    @purchase_detail = @purchase.details.find(params[:id])
    
    if @purchase_detail.quantity_print.to_f == 0
      @purchase_detail.quantity_print = ""
    end
    if @purchase_detail.price.to_f == 0
      @purchase_detail.price = ""
    end
    if @purchase_detail.discount.to_f == 0
      @purchase_detail.discount = ""
    end
  end

  # POST /purchase_details
  # POST /purchase_details.json
  def create
    get_data
    @purchase_detail = @purchase.details.create(params[:purchase_detail])
    get_data
  end

  # PUT /purchase_details/1
  # PUT /purchase_details/1.json
  def update
    get_data
    @purchase_detail = @purchase.details.find(params[:id])
    @purchase_detail.update_attributes(params[:purchase_detail])
    get_data
  end

  # DELETE /purchase_details/1
  # DELETE /purchase_details/1.json
  def destroy
    get_data
    @purchase_detail = @purchase.details.find(params[:id])
    @purchase_detail.destroy
    get_data
  end
end

app/helpers/purchase_details_helper.rb
module PurchaseDetailsHelper
end

app/views/purchase_details/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_for([@purchase, @purchase_detail], :html => { :class => "form-horizontal" }, :remote => true) do |f| %>
      <% if @purchase_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@purchase_detail.errors.count, "error") %> prohibited this purchase_detail from being saved:</h2>

          <ul>
          <% @purchase_detail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :product, "#{t 'purchase.detail.product'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.hidden_field :product_id %>
          <% if @purchase_detail.product_id.blank? %>
            <%= text_field_tag :product_name, nil, :placeholder => "#{t 'purchase.detail.product_placeholder'}", :readonly => true, :required => true, :class => "form-control" %>
          <% else %>
            <%= text_field_tag :product_name, @purchase_detail.try(:product_detail), :placeholder => "#{t 'purchase.detail.product_placeholder'}", :readonly => true, :required => true, :class => "form-control" %>
          <% end %>
        </div>
        <div class="col-sm-1">
          <%= link_to show_product_purchase_purchase_details_path(@purchase), :class => "btn btn-default", :remote => true do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
        </div>
        <!-- 
        <div class="col-sm-1">
          <%= link_to instant_new_products_path(:purchase_id => @purchase.id), :class => "btn btn-default", :remote => true do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </div>
         -->
      </div>
      <div class="form-group">
        <%= f.label :quantity, "#{t 'purchase.detail.quantity'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8"><%= f.text_field :quantity, :required => true, :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :quantity_print, "#{t 'purchase.detail.quantity_print'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8"><%= f.text_field :quantity_print, :placeholder => "#{t 'purchase.detail.quantity_print_placeholder'}", :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :price, "#{t 'purchase.detail.price'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-1"><%= label_tag :rp, "Rp", :class => "control-label" %></div>
        <div class="col-sm-7"><%= f.text_field :price, :required => true, :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :discount, "#{t 'purchase.detail.discount'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-6"><%= f.text_field :discount, :class => "form-control" %></div>
        <div class="col-sm-1"><%= label_tag :percent, "%", :class => "control-label" %></div>
      </div>
      <div class="form-group">
        <div class="col-sm-4"></div>
        <div class="col-sm-8"><%= f.submit "#{t 'submit'}", :class => "btn btn-success btn-block", :disable_with => "#{t 'disable_with'}" %></div>
      </div>
    <% end %>
  </div>

  <div class="col-md-7">
    <div id="product_filter" style="display:none;">
      <%= form_tag(search_product_purchase_purchase_details_path, :class => "form-horizontal", :remote => true) do |f| %>
        <div class="form-group">
          <div class="col-sm-3"><%= text_field_tag :keyword, nil, :placeholder => "#{t 'product.name'}", :class => "form-control" %></div>
          <div class="col-sm-3"><%= text_field_tag :product_type, nil, :placeholder => "#{t 'product.product_type'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= text_field_tag :merk, nil, :placeholder => "#{t 'product.merk'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= text_field_tag :size, nil, :placeholder => "#{t 'product.size'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= submit_tag "#{t 'search'}", :class => "btn btn-success btn-default", :disable_with => "#{t 'disable_with'}" %></div>
        </div>
      <% end -%>
    </div>

    <div id="product_list" style="width:650px; height:350px; overflow:auto;">
    </div>
  </div>
</div>

app/views/purchase_details/_form_backup.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_for([@purchase, @purchase_detail], :html => { :class => "form-horizontal" }, :remote => true) do |f| %>
      <% if @purchase_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@purchase_detail.errors.count, "error") %> prohibited this purchase_detail from being saved:</h2>

          <ul>
          <% @purchase_detail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :product, "#{t 'purchase.detail.product'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.hidden_field :product_id %>
          <%= text_field_tag :product_name, nil, :placeholder => "#{t 'purchase.detail.product_placeholder'}", :readonly => true, :class => "form-control" %>
        </div>
        <div class="col-sm-1">
          <%= link_to show_product_purchase_purchase_details_path(@purchase), :class => "btn btn-default", :remote => true do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :quantity, "#{t 'purchase.detail.quantity'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8"><%= f.text_field :quantity, :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :quantity_print, "#{t 'purchase.detail.quantity'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-8"><%= f.text_field :quantity_print, :placeholder => "#{t 'purchase.detail.quantity_print_placeholder'}", :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :price, "#{t 'purchase.detail.price'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-1"><%= label_tag :rp, "Rp", :class => "control-label" %></div>
        <div class="col-sm-7"><%= f.text_field :price, :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <%= f.label :discount, "#{t 'purchase.detail.discount'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-6"><%= f.text_field :discount, :class => "form-control" %></div>
        <div class="col-sm-1"><%= label_tag :percent, "%", :class => "control-label" %></div>
      </div>
      <div class="form-group">
        <%= f.label :added_discount, "#{t 'purchase.detail.added_discount'}", :class => "col-sm-4 control-label" %>
        <div class="col-sm-1"><%= label_tag :rp, "Rp", :class => "control-label" %></div>
        <div class="col-sm-7"><%= f.text_field :added_discount, :class => "form-control" %></div>
      </div>
      <div class="form-group">
        <div class="col-sm-4"></div>
        <div class="col-sm-8"><%= f.submit "#{t 'submit'}", :class => "btn btn-success btn-block", :disable_with => "#{t 'disable_with'}" %></div>
      </div>
    <% end %>
  </div>

  <div class="col-md-7">
    <div id="product_filter" style="display:none;">
      <%= form_tag(search_product_purchase_purchase_details_path, :class => "form-horizontal", :remote => true) do |f| %>
        <div class="form-group">
          <div class="col-sm-9"><%= text_field_tag :keyword, nil, :placeholder => "#{t 'purchase.detail.search_product_placeholder'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= submit_tag "#{t 'search'}", :class => "btn btn-success btn-default", :disable_with => "#{t 'disable_with'}" %></div>
        </div>
      <% end -%>
    </div>

    <div id="product_list" style="width:550px; height:350px; overflow:auto;">
    </div>
  </div>
</div>

app/views/purchase_details/_product_list.html.erb
<%= will_paginate @products, :params => {:controller => "purchase_details", :action => "show_product", :purchase_id => @purchase.id, :keyword => @keyword}, :class => "apple_pagination" %>

<table class="table table-condensed table-striped">
  <tr>
    <th width="1%"></th>
    <th>
      <% if @column=="name" %>
        <% if @direction=="ASC" %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "name", :direction => "DESC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.name' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% else %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "name", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.name' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
      <% else %>
        <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "name", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
          <%= t 'product.name' %>
        <% end %>
      <% end %>
    </th>

    <th>
      <% if @column=="product_type" %>
        <% if @direction=="ASC" %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "product_type", :direction => "DESC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.product_type' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% else %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "product_type", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.product_type' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
      <% else %>
        <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "product_type", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
          <%= t 'product.product_type' %>
        <% end %>
      <% end %>
    </th>
    
    <th>
      <% if @column=="merk" %>
        <% if @direction=="ASC" %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "merk", :direction => "DESC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.merk' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% else %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "merk", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.merk' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
      <% else %>
        <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "merk", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
          <%= t 'product.merk' %>
        <% end %>
      <% end %>
    </th>

    <th>
      <% if @column=="size" %>
        <% if @direction=="ASC" %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "size", :direction => "DESC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.size' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% else %>
          <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "size", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
            <%= t 'product.size' %>
          <% end %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
      <% else %>
        <%= link_to sort_product_purchase_purchase_details_path(@purchase.id, :column => "size", :direction => "ASC", :keyword => @keyword, :product_type => @product_type, :merk => @merk, :size => @size), :remote => true do %>
          <%= t 'product.size' %>
        <% end %>
      <% end %>
    </th>
  </tr>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td> 
        <%= link_to pick_product_purchase_purchase_details_path(@purchase.id, :product_id => product.id), :remote => true, :class => "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-ok"></span>
        <% end -%>
    </td>
    <td><%= product.name %></td>
    <td><%= product.product_type %></td>
    <td><%= product.merk %></td>
    <td><%= product.size %></td>
  </tr>
<% end %>
</table>

app/views/purchase_details/_table.html.erb
<table id="purchase_detail_table" class="table table-condensed table-striped">
  <tr>
    <th><%= t 'purchase.detail.product' %></th>
    <th class="text-right"><%= t 'purchase.detail.quantity' %></th>
    <th class="text-right"><%= t 'purchase.detail.quantity_print' %></th>
    <th class="text-right"><%= t 'purchase.detail.price_rp' %></th>
    <th class="text-right"><%= t 'purchase.detail.discount_%' %></th>
    <th class="text-right"><%= t 'purchase.detail.amount_rp' %></th>
    <th class="text-right"><%= link_to "#{t 'new'}", new_purchase_purchase_detail_path(@purchase), :class => "btn btn-default btn-xs", :remote => true if @purchase.status==0 %></th>
  </tr>

<% @purchase.details.each do |purchase_detail| %>
  <tr>
    <td><%= purchase_detail.product_detail %></td>
    <td class="text-right"><%= precision(purchase_detail.quantity) %></td>
    <td class="text-right"><%= precision(purchase_detail.quantity_print) %></td>
    <td class="text-right"><%= precision(purchase_detail.price) %></td>
    <td class="text-right"><%= precision(purchase_detail.discount) %></td>
    <td class="text-right"><%= precision(purchase_detail.amount) %></td>
    <td class="text-right">
      <%= link_to "#{t 'edit'}", edit_purchase_purchase_detail_path(@purchase, purchase_detail), :class => "btn btn-warning btn-xs", :remote => true if @purchase.status==0 %>
      <%= link_to "#{t 'delete'}", purchase_purchase_detail_path(@purchase, purchase_detail), method: :delete, data: { confirm: "#{t 'confirm'}" }, :class => "btn btn-danger btn-xs", :remote => true if @purchase.status==0 %>
    </td>
  </tr>
<% end %>
</table>

app/views/purchase_details/_table_backup.html.erb
<table id="purchase_detail_table" class="table table-condensed table-striped">
  <tr>
    <th><%= t 'purchase.detail.product' %></th>
    <th class="text-right"><%= t 'purchase.detail.quantity' %></th>
    <th class="text-right"><%= t 'purchase.detail.quantity_print' %></th>
    <th class="text-right"><%= t 'purchase.detail.price_rp' %></th>
    <th class="text-right"><%= t 'purchase.detail.discount_%' %></th>
    <th class="text-right"><%= t 'purchase.detail.added_discount_rp' %></th>
    <th class="text-right"><%= t 'purchase.detail.amount_rp' %></th>
    <th class="text-right"><%= link_to "#{t 'new'}", new_purchase_purchase_detail_path(@purchase), :class => "btn btn-default btn-xs", :remote => true if @purchase.status==0 %></th>
  </tr>

<% @purchase.details.each do |purchase_detail| %>
  <tr>
    <td><%= purchase_detail.product_detail %></td>
    <td class="text-right"><%= round_precision(purchase_detail.quantity) %></td>
    <td class="text-right"><%= round_precision(purchase_detail.quantity_print) %></td>
    <td class="text-right"><%= precision(purchase_detail.price) %></td>
    <td class="text-right"><%= precision(purchase_detail.discount) %></td>
    <td class="text-right"><%= precision(purchase_detail.added_discount) %></td>
    <td class="text-right"><%= precision(purchase_detail.amount) %></td>
    <td class="text-right">
      <%= link_to "#{t 'edit'}", edit_purchase_purchase_detail_path(@purchase, purchase_detail), :class => "btn btn-warning btn-xs", :remote => true if @purchase.status==0 %>
      <%= link_to "#{t 'delete'}", purchase_purchase_detail_path(@purchase, purchase_detail), method: :delete, data: { confirm: "#{t 'confirm'}" }, :class => "btn btn-danger btn-xs", :remote => true if @purchase.status==0 %>
    </td>
  </tr>
<% end %>
</table>

app/views/purchase_details/create.js.erb
$("#purchase_detail_table").html("<%= escape_javascript(render('table')) %>");
$("#show_footer_section").html("<%= escape_javascript(render('purchases/show_footer')) %>");
$('#general_modal').modal("hide");

app/views/purchase_details/destroy.js.erb
$("#purchase_detail_table").html("<%= escape_javascript(render('table')) %>");
$("#show_footer_section").html("<%= escape_javascript(render('purchases/show_footer')) %>");

app/views/purchase_details/edit.js.erb
$('#general_modal').modal('show');
$('#general_modal .modal-title').html("<%= escape_javascript(t 'purchase.purchase') %> - <%= escape_javascript(t 'purchase.detail.detail') %> - <%= escape_javascript(t 'edit') %>");
$('#general_modal .modal-body').html("<%= escape_javascript(render 'form') %>");

$("#sale_detail_unit_of_measure_id").empty();
// adding unit of measure default from unit of measure product
if (<%= @product_unit_default.present? %> == true)
{
	if (<%= @sale_detail.try(:unit_of_measure_id).to_i %> == <%= @product_unit_default.try(:id).to_i %>)
	{
		$("#sale_detail_unit_of_measure_id").append($("<option selected='selected'></option>").attr("value",<%= @product_unit_default.try(:id).to_i %>).text("<%= @product_unit_default.try(:name) %> (default)"))
	}
	else
	{
		$("#sale_detail_unit_of_measure_id").append($("<option></option>").attr("value",<%= @product_unit_default.try(:id).to_i %>).text("<%= @product_unit_default.try(:name) %> (default)"))
	}
};

// adding unit of measure from product detail
<% @product_units.each do |unit| %>
if (<%= @sale_detail.try(:unit_of_measure_id).to_i %> == <%= unit.try(:unit_of_measure).try(:id) %>)
{
	$("#sale_detail_unit_of_measure_id").append($("<option selected='selected'></option>").attr("value",<%= unit.try(:unit_of_measure).try(:id) %>).text("<%= unit.try(:unit_of_measure).try(:name) %>"))
}
else
{
	$("#sale_detail_unit_of_measure_id").append($("<option></option>").attr("value",<%= unit.try(:unit_of_measure).try(:id) %>).text("<%= unit.try(:unit_of_measure).try(:name) %>"))
}
<% end %>

app/views/purchase_details/new.js.erb
$('#general_modal').modal('show');
$('#general_modal .modal-title').html("<%= escape_javascript(t 'purchase.purchase') %> - <%= escape_javascript(t 'purchase.detail.detail') %> - <%= escape_javascript(t 'new') %>");
$('#general_modal .modal-body').html("<%= escape_javascript(render 'form') %>");

app/views/purchase_details/pick_product.js.erb
$("#purchase_detail_product_id").val("<%= @product.id %>");
$("#product_name").val("<%= @product.product_detail %>");
$("#purchase_detail_price").val("<%= @last_purchase_price if @last_purchase_price.to_i!=0 %>");

$("#product_filter").hide();
$("#product_list").html("");

$("#sale_detail_unit_of_measure_id").empty();
$("#sale_detail_unit_of_measure_id").append($("<option></option>").attr("value","").text("<%= t 'prompt' %> <%= t 'sale.detail.unit_of_measure' %>"))

// adding unit of measure default from unit of measure product
if (<%= @product_unit_default.present? %> == true)
{
	$("#sale_detail_unit_of_measure_id").append($("<option></option>").attr("value",<%= @product_unit_default.try(:id).to_i %>).text("<%= @product_unit_default.try(:name) %> (default)"))
};

// adding unit of measure from product detail
<% @product_units.each do |unit| %>
$("#sale_detail_unit_of_measure_id").append($("<option></option>").attr("value",<%= unit.try(:unit_of_measure).try(:id) %>).text("<%= unit.try(:unit_of_measure).try(:name) %>"))
<% end %>

app/views/purchase_details/sort_product.js.erb
$("#product_list").html("<%= escape_javascript(render('product_list')) %>");
$(".apple_pagination a").ajaxPagination();

app/views/purchase_details/update.js.erb
$("#purchase_detail_table").html("<%= escape_javascript(render('table')) %>");
$("#show_footer_section").html("<%= escape_javascript(render('purchases/show_footer')) %>");
$('#general_modal').modal("hide");