config/routes.rb
LancarAbadi::Application.routes.draw do

  resources :special_prices

  resources :system_languages do
    collection do
      get :change_language
      post :change_language_submit
    end
  end

  resources :report do
    collection do
      get :sale_filter
      get :sale
    end
  end

  resources :filter do
    collection do
      get :country
      get :province
      get :city
      get :unit_of_measure
      get :special_price
      get :category
      get :customer_group
      get :supplier
      get :customer
      get :product
      get :product_unit
      get :product_home
      get :purchase
      get :sale
      get :adjustment
    end
  end

  resources :adjustments do
    resources :adjustment_details do
      collection do
        get :show_product
        post :search_product
        get :pick_product
      end
    end

    member do
      get :print_barcode
      get :print_sticker
      get :import
      post :import_submit
    end
  end

  resources :sales do
    member do
      get :edit_footer
      get :print
    end
    
    collection do
      get :show_customer
      post :search_customer
      get :pick_customer
    end

    resources :sale_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :purchases do
    member do
      get :edit_footer
      get :print_barcode
      get :print_sticker
    end
    
    collection do
      get :show_supplier
      post :search_supplier
      get :pick_supplier
    end

    resources :purchase_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :customers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :customer_phones
  end

  resources :suppliers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :supplier_phones
    resources :supplier_categories
  end

  resources :products do
    collection do
      get :instant_new
      post :instant_create
      get :import
      post :import_submit
      get :generate_barcode
      post :generate_barcode_submit
      get :unit_index
    end

    member do
      get :unit_show
    end
    
    resources :product_details
    resources :product_purchases
  end

  resources :emp_date_details
  resources :emp_dates
  resources :emp_months
  resources :employees
  resources :company_profiles
  resources :stocks
  resources :user_menus
  resources :user_groups
  devise_for :users
  resources :customer_groups
  resources :unit_of_measures
  resources :categories
  resources :cities
  resources :provinces
  resources :countries

  scope "/admin" do
    resources :users
  end

  get "home/index"
  get "*module/home/provinces_by_country" => "home#provinces_by_country"
  get "*module/home/cities_by_province" => "home#cities_by_province"

  root to: "home#index"

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_and_belongs_to_many :user_menus

  attr_accessible :name, :user_menu_ids

  def self.pagination(page)
    paginate(:per_page => 15, :page => page)
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  def get_data_menus_all
    @main_menus = UserMenu.where(:header_id => "A").order(:sub_header_id)
    @setting_menus = UserMenu.where(:header_id => "B").order(:sub_header_id)
  end

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.order(:name).pagination(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_groups }
      format.js
    end
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @user_group = UserGroup.find(params[:id])
    get_data_menus_all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/new
  # GET /user_groups/new.json
  def new
    @user_group = UserGroup.new
    get_data_menus_all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/1/edit
  def edit
    @user_group = UserGroup.find(params[:id])
    get_data_menus_all
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    params[:user_group][:user_menu_ids] ||= []
    @user_group = UserGroup.new(params[:user_group])

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render json: @user_group, status: :created, location: @user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_groups/1
  # PUT /user_groups/1.json
  def update
    params[:user_group][:user_menu_ids] ||= []
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      if @user_group.update_attributes(params[:user_group])
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-md-10">
        <%= f.label :name, "#{t 'user_group.name'}", :class => "col-sm-1 control-label" %>
        <div class="col-sm-6"><%= f.text_field :name, :required => true, :class => "form-control" %></div>
        <div class="col-sm-5" style="color: red;"><%= label_tag :info, "*must be filled", :class => "control-label" %></div>
      </div>

      <div class="col-md-2">
        <div class="form-group">
          <div class="col-sm-1"></div>
          <div class="col-sm-11 text-right"><%= f.submit "#{t 'submit'}", :class => "btn btn-success", :disable_with => "#{t 'disable_with'}" %></div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <fieldset>
      <label class="checkbox">
        <%= check_box_tag "all", "", "", :class => "checkall" %>
        <%= label_tag "#{t 'select_all'}" %>
      </label>

      <div class="row">
        <div class="col-md-4">
          <%= render 'table_main' %>
        </div>
        <div class="col-md-4">
          <%= render 'table_setting' %>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

app/views/user_groups/_table.html.erb
<%= will_paginate @user_groups, :class => "apple_pagination" %>

<table class="table table-condensed">
  <tr style="background-color:#708DC6;">
    <th><%= t 'user_group.name' %></th>
    <th class="span4"></th>
  </tr>

<% @user_groups.each do |user_group| %>
  <% if user_group.name!="Developer" %>
  <tr>
    <td><%= user_group.name %></td>
    <td style="text-align:right;">
      <%= link_to "#{t 'show'}", user_group, :class => "btn btn-xs btn-info" %>
      <%= link_to "#{t 'user_group.edit_manage_role'}", edit_user_group_path(user_group), :class => "btn btn-xs btn-warning" %>
      <%= #link_to "#{t 'destroy'}", user_group, method: :delete, data: { confirm: "#{t 'confirm'}" }, :class => "btn btn-mini btn-danger"
       %>
    </td>
  </tr>
  <% elsif current_user.user_group.try(:name)=="Developer" %>
  <tr>
    <td><%= user_group.name %></td>
    <td style="text-align:right;">
      <%= link_to "#{t 'show'}", user_group, :class => "btn btn-xs btn-info" %>
      <%= link_to "#{t 'user_group.edit_manage_role'}", edit_user_group_path(user_group), :class => "btn btn-xs btn-warning" %>
      <%= #link_to "#{t 'destroy'}", user_group, method: :delete, data: { confirm: "#{t 'confirm'}" }, :class => "btn btn-mini btn-danger"
       %>
    </td>
  </tr>
  <% else %>
  <% end %>
<% end %>
</table>

<%= will_paginate @user_groups, :class => "apple_pagination" %>

app/views/user_groups/_table_main.html.erb
<table class="table table-condensed">
  <tr>
    <td>
      <div class="label label-default">A</div>&nbsp;
      <%= t 'layout.master.master' %>
    </td>
  </tr>

  <% @main_menus.each do |menu| %>
    <tr>
      <td>
        <% if menu.visible==true %>
          <label class="checkbox">
            <%= check_box_tag "user_group[user_menu_ids][]", menu.id, @user_group.user_menus.include?(menu) %>
            <%= menu.name %>
          </label>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/user_groups/_table_setting.html.erb
<table class="table table-condensed">
  <tr>
    <td>
      <div class="label label-default">B</div>&nbsp;
      <%= t 'layout.setting.setting' %>
    </td>
  </tr>

  <% @setting_menus.each do |menu| %>
    <tr>
      <td>
        <% if menu.visible==true %>
          <label class="checkbox">
            <%= check_box_tag "user_group[user_menu_ids][]", menu.id, @user_group.user_menus.include?(menu) %>
            <%= menu.name %>
          </label>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/user_groups/edit.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to user_groups_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;<%= t 'cancel' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'user_group.user_group' %> - <%= t 'edit' %></h4>
  </div>

  <div class="col-md-2" align="right">
    <%= link_to user_group_path(@user_group), :class => "btn btn-sm btn-success" do %>
      <%= t 'show' %>&nbsp;<span class="glyphicon glyphicon-th-list"></span>
    <% end %>
  </div>
</div>
<hr>

<%= render 'form' %>

app/views/user_groups/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to user_menus_path, :class => "btn btn-default btn-sm" do %>
      <%= t 'user_group.menu' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'user_group.user_groups' %></h4>
  </div>

  <div class="col-md-2" align="right">
    <%= link_to new_user_group_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;<%= t 'new' %>
    <% end %>
  </div>
</div>

<div id="table"><%= render 'table' %></div>

app/views/user_groups/index.js.erb
$("#table").html("<%= escape_javascript(render('table')) %>");
$(".apple_pagination a").ajaxPagination();

app/views/user_groups/new.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to user_groups_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;<%= t 'cancel' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'user_group.user_group' %> - <%= t 'new' %></h4>
  </div>

  <div class="col-md-2"></div>
</div>
<hr>

<%= render 'form' %>

app/views/user_groups/show.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to user_groups_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;<%= t 'back' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'user_group.user_group' %> - <%= t 'user_group.name' %>: <%= @user_group.name %></h4>
  </div>

  <div class="col-md-2" align="right">
    <%= link_to edit_user_group_path(@user_group), :class => "btn btn-sm btn-warning" do %>
      <%= t 'user_group.edit_manage_role' %>&nbsp;<i class="glyphicon glyphicon-pencil"></i>
    <% end %>
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-6">
    <!-- TABLE MAIN MENU -->
    <table class="table table-condensed">
      <tr>
        <td>
          <div class="label label-default">A</div>&nbsp;
          <%= t 'layout.transaction.transaction' %>
        </td>
      </tr>

      <% @main_menus.each do |menu| %>
        <tr>
          <td>
            <% if menu.visible==true %>
              <label class="checkbox">
                <%= check_box_tag "user_group[user_menu_ids][]", menu.id, @user_group.user_menus.include?(menu), :disabled => true %>
                <%= menu.name %>
              </label>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-6">
    <!-- TABLE SETTING MENU -->
    <table class="table table-condensed">
      <tr>
        <td>
          <div class="label label-default">B</div>&nbsp;
          <%= t 'layout.setting.setting' %>
        </td>
      </tr>

      <% @setting_menus.each do |menu| %>
        <tr>
          <td>
            <% if menu.visible==true %>
              <label class="checkbox">
                <%= check_box_tag "user_group[user_menu_ids][]", menu.id, @user_group.user_menus.include?(menu), :disabled => true %>
                <%= menu.name %>
              </label>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>