config/routes.rb
LancarAbadi::Application.routes.draw do

  resources :special_prices

  resources :system_languages do
    collection do
      get :change_language
      post :change_language_submit
    end
  end

  resources :report do
    collection do
      get :sale_filter
      get :sale
    end
  end

  resources :filter do
    collection do
      get :country
      get :province
      get :city
      get :unit_of_measure
      get :special_price
      get :category
      get :customer_group
      get :supplier
      get :customer
      get :product
      get :product_unit
      get :product_home
      get :purchase
      get :sale
      get :adjustment
    end
  end

  resources :adjustments do
    resources :adjustment_details do
      collection do
        get :show_product
        post :search_product
        get :pick_product
      end
    end

    member do
      get :print_barcode
      get :print_sticker
      get :import
      post :import_submit
    end
  end

  resources :sales do
    member do
      get :edit_footer
      get :print
    end
    
    collection do
      get :show_customer
      post :search_customer
      get :pick_customer
    end

    resources :sale_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :purchases do
    member do
      get :edit_footer
      get :print_barcode
      get :print_sticker
    end
    
    collection do
      get :show_supplier
      post :search_supplier
      get :pick_supplier
    end

    resources :purchase_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :customers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :customer_phones
  end

  resources :suppliers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :supplier_phones
    resources :supplier_categories
  end

  resources :products do
    collection do
      get :instant_new
      post :instant_create
      get :import
      post :import_submit
      get :generate_barcode
      post :generate_barcode_submit
      get :unit_index
    end

    member do
      get :unit_show
    end
    
    resources :product_details
    resources :product_purchases
  end

  resources :emp_date_details
  resources :emp_dates
  resources :emp_months
  resources :employees
  resources :company_profiles
  resources :stocks
  resources :user_menus
  resources :user_groups
  devise_for :users
  resources :customer_groups
  resources :unit_of_measures
  resources :categories
  resources :cities
  resources :provinces
  resources :countries

  scope "/admin" do
    resources :users
  end

  get "home/index"
  get "*module/home/provinces_by_country" => "home#provinces_by_country"
  get "*module/home/cities_by_province" => "home#cities_by_province"

  root to: "home#index"

end

app/models/system_language.rb
class SystemLanguage < ActiveRecord::Base
  attr_accessible :active, :initial, :name
end

app/controllers/system_languages_controller.rb
class SystemLanguagesController < ApplicationController
  def change_language
    @system_languages = SystemLanguage.order(:name)
  end

  def change_language_submit
    SystemLanguage.all.each do |language|
      language.update_attributes(:active => false)
    end

    SystemLanguage.find(params[:language_id]).update_attributes(:active => true)

    respond_to do |format|
      format.html {redirect_to company_profiles_path, notice: 'System Language was successfully changed.' }
    end
  end
end

app/helpers/system_languages_helper.rb
module SystemLanguagesHelper
end

app/views/system_languages/_form.html.erb
<%= form_tag change_language_submit_system_languages_path, :method => "post", :class => "form-horizontal" do %>
<div class="form-group">
  <div class="col-sm-10">
    <%= select_tag(:language_id, options_from_collection_for_select(@system_languages, 'id', 'name'), :prompt => "#{t 'prompt'} #{t 'language.language'}", :class => "form-control") %>
  </div>
  <div class="col-sm-2">
    <%= submit_tag "#{t 'process'}", :disable_with => "#{t 'disable_with'}", :class => "btn btn-success" %>
  </div>
</div>
<% end %>

app/views/system_languages/change_language.js.erb
$('#general_modal').modal('show');
$('#general_modal .modal-title').html("<%= escape_javascript(t 'language.change_language') %>");
$('#general_modal .modal-body').html("<%= escape_javascript(render 'form') %>");

app/views/system_languages/edit.html.erb
<h1>Editing system_language</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_language %> |
<%= link_to 'Back', system_languages_path %>

app/views/system_languages/index.html.erb
<h1>Listing system_languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Initial</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @system_languages.each do |system_language| %>
  <tr>
    <td><%= system_language.name %></td>
    <td><%= system_language.initial %></td>
    <td><%= system_language.active %></td>
    <td><%= link_to 'Show', system_language %></td>
    <td><%= link_to 'Edit', edit_system_language_path(system_language) %></td>
    <td><%= link_to 'Destroy', system_language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System language', new_system_language_path %>

app/views/system_languages/new.html.erb
<h1>New system_language</h1>

<%= render 'form' %>

<%= link_to 'Back', system_languages_path %>

app/views/system_languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @system_language.name %>
</p>

<p>
  <b>Initial:</b>
  <%= @system_language.initial %>
</p>

<p>
  <b>Active:</b>
  <%= @system_language.active %>
</p>


<%= link_to 'Edit', edit_system_language_path(@system_language) %> |
<%= link_to 'Back', system_languages_path %>