config/routes.rb
LancarAbadi::Application.routes.draw do

  resources :special_prices

  resources :system_languages do
    collection do
      get :change_language
      post :change_language_submit
    end
  end

  resources :report do
    collection do
      get :sale_filter
      get :sale
    end
  end

  resources :filter do
    collection do
      get :country
      get :province
      get :city
      get :unit_of_measure
      get :special_price
      get :category
      get :customer_group
      get :supplier
      get :customer
      get :product
      get :product_unit
      get :product_home
      get :purchase
      get :sale
      get :adjustment
    end
  end

  resources :adjustments do
    resources :adjustment_details do
      collection do
        get :show_product
        post :search_product
        get :pick_product
      end
    end

    member do
      get :print_barcode
      get :print_sticker
      get :import
      post :import_submit
    end
  end

  resources :sales do
    member do
      get :edit_footer
      get :print
    end
    
    collection do
      get :show_customer
      post :search_customer
      get :pick_customer
    end

    resources :sale_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :purchases do
    member do
      get :edit_footer
      get :print_barcode
      get :print_sticker
    end
    
    collection do
      get :show_supplier
      post :search_supplier
      get :pick_supplier
    end

    resources :purchase_details do
      collection do
        get :show_product
        post :search_product
        get :sort_product
        get :pick_product
      end
    end
  end

  resources :customers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :customer_phones
  end

  resources :suppliers do
    collection do
      get :import
      post :import_submit
      get :import_phone
      post :import_phone_submit
    end
    
    resources :supplier_phones
    resources :supplier_categories
  end

  resources :products do
    collection do
      get :instant_new
      post :instant_create
      get :import
      post :import_submit
      get :generate_barcode
      post :generate_barcode_submit
      get :unit_index
    end

    member do
      get :unit_show
    end
    
    resources :product_details
    resources :product_purchases
  end

  resources :emp_date_details
  resources :emp_dates
  resources :emp_months
  resources :employees
  resources :company_profiles
  resources :stocks
  resources :user_menus
  resources :user_groups
  devise_for :users
  resources :customer_groups
  resources :unit_of_measures
  resources :categories
  resources :cities
  resources :provinces
  resources :countries

  scope "/admin" do
    resources :users
  end

  get "home/index"
  get "*module/home/provinces_by_country" => "home#provinces_by_country"
  get "*module/home/cities_by_province" => "home#cities_by_province"

  root to: "home#index"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :customer_group
  has_many :details, :class_name => "SaleDetail"
  
  attr_accessible :added_discount, :amount_after_discount, :discount, :discount_amount, :notes, :si_id, :sub_amount, :tax, :tax_amount, :total_amount, :transaction_date, :customer_id, :customer_group_id, :status

  before_create :id_generator
  before_update :sum_total_amount
  before_save :get_customer_group
  after_update :populate_stock

  def self.pagination(page)
    paginate(:per_page => 20, :page => page)
  end

  def customer_name
  	customer.try(:name)
  end

  def customer_group_name
    customer_group.try(:name)
  end

  def id_generator
  	# si_id = SI-YYMM-0001
  	last_trans = Sale.last
  	
    new_id = 1
    if last_trans.present?
  		new_id = last_trans.try(:si_id)[8,4].to_i + 1 if last_trans.created_at.localtime.strftime("%Y")==Time.now.strftime("%Y") && last_trans.created_at.localtime.strftime("%m")==Time.now.strftime("%m")
    end

  	self.si_id = "SI-#{Time.now.strftime("%y")}#{Time.now.strftime("%m")}-%04i" % new_id
  end

  def get_customer_group
    self.customer_group_id = self.customer.try(:customer_group_id)
  end

  def sum_sub_amount
    self.sub_amount = self.details.sum('amount').to_f
    self.discount_amount = self.sub_amount * (self.discount.to_f/100)
    self.amount_after_discount = self.sub_amount - self.discount_amount
    if self.tax==true
      self.tax_amount = (self.amount_after_discount - self.added_discount.to_f) * 0.1
    else
      self.tax_amount = 0
    end
    self.total_amount = self.amount_after_discount - self.added_discount.to_f + self.tax_amount
    self.save
  end

  def sum_total_amount
    self.sub_amount = self.details.sum('amount').to_f
    self.discount_amount = self.sub_amount * (self.discount.to_f/100)
    self.amount_after_discount = self.sub_amount - self.discount_amount
    if self.tax==true
      self.tax_amount = (self.amount_after_discount - self.added_discount.to_f) * 0.1
    else
      self.tax_amount = 0
    end
    self.total_amount = self.amount_after_discount - self.added_discount.to_f + self.tax_amount
  end

  def populate_stock
    sale = Sale.find(self.id)
    sale.details.each do |detail| # looping all details
      stock = Stock.find_by_product_id(detail.product_id.to_i)
      if self.status.to_i==1 # checking sale status
        if stock.blank?
          Stock.create(:product_id => detail.product_id, 
                       :stock_real => 0, 
                       :stock_ready => 0, 
                       :unit_of_measure_id => detail.product.try(:unit_of_measure_id), 
                       :last_purchase => "", 
                       :last_sale => Time.now.localtime.strftime("%Y-%m-%d"),
                       :notes => "")
        else
          stock.update_attributes(:stock_real => stock.stock_real.to_f - detail.quantity.to_f, 
                                  :stock_ready => stock.stock_ready.to_f - detail.quantity.to_f, # need to be moved on sale detail
                                  :last_sale => Time.now.localtime.strftime("%Y-%m-%d"))
        end
      elsif self.status.to_i==5 # checking sale status
        if stock.blank?
            Stock.create(:product_id => detail.product_id, 
                         :stock_real => detail.quantity.to_f, 
                         :stock_ready => detail.quantity.to_f, 
                         :unit_of_measure_id => detail.product.try(:unit_of_measure_id), 
                         :last_purchase => "", 
                         :last_sale => "",
                         :notes => "")
          else
            last_closed_sale = Sale.order(:id).where(:status => 1).last

            if last_closed_sale.present?
              stock.update_attributes(:stock_real => stock.stock_real.to_f + detail.quantity.to_f, 
                                      :stock_ready => stock.stock_ready.to_f + detail.quantity.to_f, 
                                      :last_sale => last_closed_sale.try(:transaction_date).to_time.localtime.strftime("%Y-%m-%d"))
            else
              stock.update_attributes(:stock_real => stock.stock_real.to_f + detail.quantity.to_f, 
                                      :stock_ready => stock.stock_ready.to_f + detail.quantity.to_f)
            end
          end
      else
      end # checking sale status
    end # looping all details
  end

  def self.filter_month(id)
    where("EXTRACT(MONTH FROM transaction_date) = ?", "#{id}")
  end

  def self.filter_year(id)
    where("EXTRACT(YEAR FROM transaction_date) = ?", "#{id}")
  end

  def self.filter_transaction_period(start_date, end_date)
    if start_date.present? and end_date.blank?
      where("sales.transaction_date >= ?", start_date)
    elsif start_date.blank? and end_date.present?
      where("sales.transaction_date <= ?", "#{end_date} 23:59:59")
    elsif start_date.present? and end_date.present?
      where("sales.transaction_date BETWEEN ? AND ?", start_date, "#{end_date} 23:59:59")
    else
      where("EXTRACT(MONTH FROM sales.transaction_date)=EXTRACT(MONTH FROM CURRENT_DATE) AND EXTRACT(YEAR FROM sales.transaction_date)=EXTRACT(YEAR FROM CURRENT_DATE)")
    end
  end

  def self.filter_customer(id)
    if id!=0
      where(:customer_id => id)
    else
      scoped
    end
  end

  def self.filter_status(id)
    if id.present?
      where(:status => id)
    else
      scoped
    end
  end

  def self.sort_report(order_by)
    if order_by=="date_asc"
      order(:transaction_date)
    elsif order_by=="date_dsc"
      order(:transaction_date).reverse_order
    elsif order_by=="customer_asc"
      joins(:customer).order("customers.name ASC, total_amount DESC")
    elsif order_by=="customer_dsc"
      joins(:customer).order("customers.name DSC, total_amount DESC")
    elsif order_by=="amount_asc"
      order(:total_amount)
    elsif order_by=="amount_dsc"
      order(:total_amount).reverse_order
    else
      order(:created_at).reverse_order
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def get_customer
    @customers = Customer.search_customer(params[:keyword])
    .order(:name)
    .paginate(:page => params[:page], :per_page => 100)

    @keyword = params[:keyword] if params[:keyword].present?
  end

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale
    .where("EXTRACT(MONTH FROM transaction_date)=EXTRACT(MONTH FROM CURRENT_DATE) AND EXTRACT(YEAR FROM transaction_date)=EXTRACT(YEAR FROM CURRENT_DATE)")
    .order(:created_at).reverse_order
    .pagination(params[:page])

    @customers = Customer.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
      format.js
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
      format.pdf do
        pdf = SaleIndividualPdf.new(@sale.id, view_context, ApplicationController.helpers.get_company_identity)
        send_data pdf.render, filename: "#{I18n.t 'sale.sales_invoice'} #{Time.now.strftime("%Y-%m-%d %H:%M:%S")}.pdf",
        type: "application/pdf", :disposition => "inline"
      end
    end
  end

  def show_customer
    get_customer
  end

  def search_customer
    get_customer
  end

  def pick_customer
    @customer = Customer.find(params[:customer_id])
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
    
    if @sale.status.to_i!=0
      redirect_to @sale
    else
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def edit_footer
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :si_id, "#{t 'sale.si_id'}", :class => "col-sm-4 control-label" %>
    <div class="col-sm-7"><%= f.text_field :si_id, :placeholder => "#{t 'sale.si_id_placeholder'}", :readonly => true, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label :transaction_date, "#{t 'sale.transaction_date'}", :class => "col-sm-4 control-label" %>
    <div class="col-sm-7"><%= f.text_field :transaction_date, :class => "form-control", :value => "#{Time.now.strftime('%Y-%m-%d')}" %></div>
  </div>
  <div class="form-group">
    <%= f.label :customer, "#{t 'sale.customer'}", :class => "col-sm-4 control-label" %>
    <div class="col-sm-5">
      <%= f.hidden_field :customer_id %>
      <% if @sale.customer_id.nil? %>
        <%= text_field_tag :customer_name, nil, :placeholder => "#{t 'sale.customer_placeholder'}", :readonly => true, :class => "form-control" %>
      <% else %>
        <%= text_field_tag :customer_name, @sale.customer_name, :placeholder => "#{t 'sale.customer_placeholder'}", :readonly => true, :class => "form-control" %>
      <% end -%>
    </div>
    <div class="col-sm-1">
      <%= link_to show_customer_sales_path, :remote => true, :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-search"></span>
      <% end -%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notes, "#{t 'sale.notes'}", :class => "col-sm-4 control-label" %>
    <div class="col-sm-7"><%= f.text_area :notes, :rows => 3, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-sm-4"></div>
    <div class="col-sm-7"><%= f.submit "#{t 'submit'}", :class => "btn btn-success btn-block", :disable_with => "#{t 'disable_with'}" %></div>
  </div>
<% end %>

app/views/sales/_show_footer_backup.html.erb
<div class="row">
  <div class="col-sm-8"></div>

  <div class="col-sm-4">
    <hr>
    <table>
      <tr>
        <th class="text-right" width="200"><%= t 'sale.sub_amount' %>:</th>
        <th width="50">&nbsp;Rp</th>
        <th class="text-right" width="150"><%= precision(@sale.sub_amount) %></th>
        <th width="50">
          <% if @sale.status==0 %>
            <%= link_to edit_footer_sale_path(@sale), :class => "btn btn-warning btn-xs", :remote => true do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          <% end -%>
        </th>
      </tr>
      <tr>
        <td class="text-right"><%= "#{t 'sale.discount'} (#{precision(@sale.discount)}%)" %>:</td>
        <td>&nbsp;Rp</td>
        <td class="text-right"><%= precision(@sale.discount_amount) %></td>
        <td></td>
      </tr>
      <tr>
        <th class="text-right"><%= t 'sale.amount_after_discount' %>:</th>
        <th>&nbsp;Rp</th>
        <th class="text-right"><%= precision(@sale.amount_after_discount) %></th>
        <th></th>
      </tr>
      <tr>
        <td class="text-right"><%= t 'sale.added_discount' %>:</td>
        <td>&nbsp;Rp</td>
        <td class="text-right"><%= precision(@sale.added_discount) %></td>
        <td></td>
      </tr>
      <tr>
        <td class="text-right"><%= t 'sale.tax' %>:</td>
        <td></td>
        <td class="text-right"><%= "&#10004;".html_safe if @sale.tax==true %></td>
        <td></td>
      </tr>
      <tr>
        <td class="text-right"><%= t 'sale.tax_amount' %>:</td>
        <td>&nbsp;Rp</td>
        <td class="text-right"><%= precision(@sale.tax_amount) %></td>
        <td></td>
      </tr>
      <tr>
        <th class="text-right"><%= t 'sale.total_amount' %>:</th>
        <th>&nbsp;Rp</th>
        <th class="text-right"><%= precision(@sale.total_amount) %></th>
        <th></th>
      </tr>
    </table>
  </div>
</div>

app/views/sales/_show_print_only.html.erb
<% counter=0; row_number=0; total=0; grand_total=0; @sale.details.each do |sale_detail| %>
  <% counter+=1; if counter==1 %>
    <!-- PRINT HEADER -->
    <table id="table_hidden">
      <tr>
        <td width="400"><%= company_name %></td>
        <th class="text-center" width="500"><%= (t 'sale.sales_invoice').upcase %></th>
        <td class="text-right" width="400">Kepada Yth.:&nbsp;<%= (@sale.customer.try(:name)).upcase %></td>
      </tr>
      <tr >
        <td><%= company_address %></td>
        <th class="text-center">Nota No: <%= @sale.si_id %></th>
        <td class="text-right"><%= @sale.customer.try(:address) %></td>
      </tr>
      <tr>
        <td><%= company_telephone %></td>
        <th class="text-center">Ponorogo, <%= @sale.transaction_date.to_time.localtime.strftime('%d %B %Y') %></th>
        <td class="text-right"><%= "#{@sale.customer.try(:city).try(:name)}-#{@sale.customer.try(:province).try(:name)}" %></td>
      </tr>
    </table>

    <table id="sale_detail_table" class="" border=1>
      <tr>
        <th><%= t 'row_number' %></th>
        <th width="50%"><%= t 'sale.detail.product' %></th>
        <th width="7%" class="text-right"><%= t 'sale.detail.quantity' %></th>
        <th class="text-center"><%= t 'sale.detail.unit' %></th>
        <th width="12%" class="text-right"><%= t 'sale.detail.price_rp' %></th>
        <th class="text-right"><%= t 'sale.detail.discount_%' %></th>
        <th width="12%" class="text-right"><%= t 'sale.detail.amount_rp' %></th>
        <th class="text-right" id="button_column"><%= link_to "#{t 'new'}", new_sale_sale_detail_path(@sale), :id => "btn", :class => "btn btn-default btn-xs", :remote => true if @sale.status==0 %></th>
      </tr>
      <tr>
        <td class="text-right"><%= row_number+=1 %>.</td>
        <td><%= sale_detail.product_detail %></td>
        <td class="text-right"><%= precision(sale_detail.quantity) %></td>
        <td class="text-center"><%= sale_detail.try(:unit_of_measure).try(:name) %></td>
        <td class="text-right"><%= precision(sale_detail.price) %></td>
        <td class="text-right"><%= precision(sale_detail.discount) %></td>
        <td class="text-right"><%= precision(sale_detail.amount) %><% total+=sale_detail.amount.to_f; grand_total+=sale_detail.amount.to_f %></td>
        <td class="text-right" id="button_column">
          <%= link_to "#{t 'edit'}", edit_sale_sale_detail_path(@sale, sale_detail), :id => "btn", :class => "btn btn-warning btn-xs", :remote => true if @sale.status==0 %>
          <%= link_to "#{t 'delete'}", sale_sale_detail_path(@sale, sale_detail), method: :delete, data: { confirm: "#{t 'confirm'}" }, :id => "btn", :class => "btn btn-danger btn-xs", :remote => true if @sale.status==0 %>
        </td>
      </tr>
  <% elsif counter==15 %>
      <tr>
        <td class="text-right"><%= row_number+=1 %>.</td>
        <td><%= sale_detail.product_detail %></td>
        <td class="text-right"><%= precision(sale_detail.quantity) %></td>
        <td class="text-center"><%= sale_detail.try(:unit_of_measure).try(:name) %></td>
        <td class="text-right"><%= precision(sale_detail.price) %></td>
        <td class="text-right"><%= precision(sale_detail.discount) %></td>
        <td class="text-right"><%= precision(sale_detail.amount) %><% total+=sale_detail.amount.to_f; grand_total+=sale_detail.amount.to_f %></td>
        <td class="text-right" id="button_column">
          <%= link_to "#{t 'edit'}", edit_sale_sale_detail_path(@sale, sale_detail), :id => "btn", :class => "btn btn-warning btn-xs", :remote => true if @sale.status==0 %>
          <%= link_to "#{t 'delete'}", sale_sale_detail_path(@sale, sale_detail), method: :delete, data: { confirm: "#{t 'confirm'}" }, :id => "btn", :class => "btn btn-danger btn-xs", :remote => true if @sale.status==0 %>
        </td>
      </tr>
    </table>

    <div class="row">
      <div class="col-sm-8"></div>
      <div class="col-sm-4">
        <table id="table_hidden">
          <tr>
            <th class="text-right" width="200"><%= t 'sale.total_amount' %>:</th>
            <th width="50">&nbsp;Rp</th>
            <th class="text-right" width="150"><%= precision(total) %></th>
            <th width="50"></th>
          </tr>
        </table>
      </div>
    </div>
    <br>
    <% counter=0; total=0 %>
  <% else %>
      <tr>
        <td class="text-right"><%= row_number+=1 %>.</td>
        <td><%= sale_detail.product_detail %></td>
        <td class="text-right"><%= precision(sale_detail.quantity) %></td>
        <td class="text-center"><%= sale_detail.try(:unit_of_measure).try(:name) %></td>
        <td class="text-right"><%= precision(sale_detail.price) %></td>
        <td class="text-right"><%= precision(sale_detail.discount) %></td>
        <td class="text-right"><%= precision(sale_detail.amount) %><% total+=sale_detail.amount.to_f; grand_total+=sale_detail.amount.to_f %></td>
        <td class="text-right" id="button_column">
          <%= link_to "#{t 'edit'}", edit_sale_sale_detail_path(@sale, sale_detail), :id => "btn", :class => "btn btn-warning btn-xs", :remote => true if @sale.status==0 %>
          <%= link_to "#{t 'delete'}", sale_sale_detail_path(@sale, sale_detail), method: :delete, data: { confirm: "#{t 'confirm'}" }, :id => "btn", :class => "btn btn-danger btn-xs", :remote => true if @sale.status==0 %>
        </td>
      </tr>
  <% end %>
<% end %>

<% if counter!=15 %>
  </table>

  <div class="row">
    <div class="col-sm-8"></div>
    <div class="col-sm-4">
      <table id="table_hidden">
        <tr>
          <th class="text-right" width="200"><%= t 'sale.total_amount' %>:</th>
          <th width="50">&nbsp;Rp</th>
          <th class="text-right" width="150"><%= precision(total) %></th>
          <th width="50"></th>
        </tr>
        <tr>
          <th colspan="3"><hr></th>
        </tr>
        <tr>
          <th class="text-right" width="200"><%= t 'sale.grand_amount' %>:</th>
          <th width="50">&nbsp;Rp</th>
          <th class="text-right" width="150"><%= precision(grand_total) %></th>
          <th width="50"></th>
        </tr>
      </table>
    </div>
  </div>
  
  <table border=1 id="table_hidden">
    <tr>
      <td class="text-center">
        Pengirim,<br><br><br>&nbsp;(....................)&nbsp;
      </td>
      <td class="text-center">
        Penerima,<br><br><br>&nbsp;(....................)&nbsp;
      </td>
    </tr>
  </table>
<% else %>
  <div class="row">
    <div class="col-sm-8"></div>
    <div class="col-sm-4">
      <table id="table_hidden">
        <tr>
          <th colspan="3"><hr></th>
        </tr>
        <tr>
          <th class="text-right" width="200"><%= t 'sale.grand_amount' %>:</th>
          <th width="50">&nbsp;Rp</th>
          <th class="text-right" width="150"><%= precision(grand_total) %></th>
          <th width="50"></th>
        </tr>
      </table>
    </div>
  </div>
  
  <table border=1 id="table_hidden">
    <tr>
      <td class="text-center">
        Pengirim,<br><br><br>&nbsp;(....................)&nbsp;
      </td>
      <td class="text-center">
        Penerima,<br><br><br>&nbsp;(....................)&nbsp;
      </td>
    </tr>
  </table>
<% end %>

app/views/sales/_table.html.erb
<%= will_paginate @sales, :class => "apple_pagination" %>

<table class="table table-condensed">
  <tr>
    <th><%= t 'sale.si_id' %></th>
    <th><%= t 'sale.transaction_date' %></th>
    <th><%= t 'sale.customer' %></th>
    <th><%= t 'sale.customer_group' %></th>
    <th><%= t 'sale.notes' %></th>
    <th class="text-right"><%= t 'sale.total_amount' %></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr class="status_<%= sale.status.to_i %>">
    <td><%= sale.si_id %></td>
    <td><%= date(sale.transaction_date) %></td>
    <td><%= sale.customer_name %></td>
    <td><%= sale.customer_group_name %></td>
    <td><%= sale.notes %></td>
    <td class="text-right"><%= precision(sale.total_amount) %></td>
    <td class="text-right">
        <%= link_to "#{t 'edit'}", edit_sale_path(sale), :class => "btn btn-warning btn-xs" if sale.status.to_i==0 %>
        <%= link_to "#{t 'show'}", sale, :class => "btn btn-primary btn-xs" %>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @sales, :class => "apple_pagination" %>

app/views/sales/edit.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to sales_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;<%= t 'back' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'sale.sale' %> - <%= t 'edit' %></h4>
  </div>

  <div class="col-md-2" align="right">
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>

  <div class="col-md-6">
    <div id="customer_filter" style="display:none;">
      <%= form_tag(search_customer_sales_path, :html => { :class => "form-horizontal" }, :remote => true) do %>
        <div class="form-group">
          <div class="col-sm-10"><%= text_field_tag :keyword, nil, :placeholder => "#{t 'sale.search_customer_placeholder'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= submit_tag "#{t 'search'}", :class => "btn btn-success btn-block", :disable_with => "#{t 'disable_with'}" %></div>
        </div>
      <% end -%>
    </div>

    <div id="customer_list">
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to sales_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>&nbsp;<%= t 'back' %>
    <% end %>
  </div>
  
  <div class="col-md-8">
    <h4 align="center"><%= t 'sale.sale' %> - <%= t 'new' %></h4>
  </div>

  <div class="col-md-2" align="right">
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>

  <div class="col-md-6">
    <div id="customer_filter" style="display:none;">
      <%= form_tag(search_customer_sales_path, :class => "form-horizontal", :remote => true) do %>
        <div class="form-group">
          <div class="col-sm-10"><%= text_field_tag :keyword, nil, :placeholder => "#{t 'sale.search_customer_placeholder'}", :class => "form-control" %></div>
          <div class="col-sm-2"><%= submit_tag "#{t 'search'}", :class => "btn btn-success btn-block", :disable_with => "#{t 'disable_with'}" %></div>
        </div>
      <% end -%>
    </div>

    <div id="customer_list" style="height:350px; overflow:auto;">
    </div>
  </div>
</div>

app/views/sales/pick_customer.js.erb
$("#sale_customer_id").val("<%= @customer.id %>");
$("#customer_name").val("<%= @customer.name %>");

$("#customer_filter").hide();
$("#customer_list").html("");